stages:
  - build

truchas intel:
  stage: build
  tags: ["intel"]
  image: registry.gitlab.com/truchas/ci-images/ci-test:tpl-d6fdf1f
  script:
    - sudo apt-get update
    - sudo apt-get install -yq --no-install-recommends python3-numpy python3-scipy python3-h5py openssh-client
    - bash ci/build.sh
