stages:
  - build
  - test
  - deploy

build truchas binary:
  stage: build
  needs: []
  tags: ["intel"]
  image: registry.gitlab.com/truchas/ci-images/ci-test:tpl-mpich-centos7-2db5337
  script:
    - sudo yum install -y python3 openssh-clients bzip2
    - curl -O https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/p/patchelf-0.11-1.el7.x86_64.rpm
    - sudo yum install -y ./patchelf-0.11-1.el7.x86_64.rpm
    - sudo pip3 install numpy h5py
    - sudo rm -f /usr/bin/python
    - sudo ln -s /usr/bin/python3 /usr/bin/python
    - bash ci/build.sh
    - cd build/inst/bin/
    - export INTELDIR=/opt/intel/
    - export LD_LIBRARY_PATH=$INTELDIR/lib/intel64
    - ../../../ci/make_dist.py
  artifacts:
    paths:
      - build/inst/bin/t-*
      - build/inst/bin/truchas-*.tar.bz2
    when: always

test truchas intel (Release):
  stage: build
  needs: []
  tags: ["intel"]
  image: registry.gitlab.com/truchas/ci-images/ci-test:tpl-mpich-centos7-2db5337
  script:
    - sudo yum install -y python3 openssh-clients
    - sudo pip3 install numpy scipy h5py
    - sudo rm -f /usr/bin/python
    - sudo ln -s /usr/bin/python3 /usr/bin/python
    - bash ci/build.sh
    - cd build
    - export INTELDIR=/opt/intel/
    - export LD_LIBRARY_PATH=$INTELDIR/lib/intel64
    - ctest --output-on-failure

test truchas intel (Debug):
  stage: build
  needs: []
  tags: ["intel"]
  image: registry.gitlab.com/truchas/ci-images/ci-test:tpl-mpich-centos7-2db5337
  script:
    - sudo yum install -y python3 openssh-clients
    - sudo pip3 install numpy scipy h5py
    - sudo rm -f /usr/bin/python
    - sudo ln -s /usr/bin/python3 /usr/bin/python
    - bash ci/build.sh Debug
    - cd build
    - export INTELDIR=/opt/intel/
    - export LD_LIBRARY_PATH=$INTELDIR/lib/intel64
    - ctest --output-on-failure

test truchas binary:
  stage: test
  needs: ["build truchas binary"]
  image: ubuntu:18.04
  script:
    - tar xaf build/inst/bin/truchas-*.tar.bz2
    - cd truchas-*/
    - ./bin/t-linux.x86_64.intel -h

upload truchas binary:
  stage: deploy
  needs: ["build truchas binary"]
  image: ubuntu:20.04
  variables:
    GIT_FETCH_EXTRA_FLAGS: --tags --prune --prune-tags
    GIT_DEPTH: 0 # fetch all commits and tags
  script:
    - apt-get update
    - apt-get install -yq --no-install-recommends git python3 python3-pip python3-setuptools
    - pip3 install aiohttp==3.5.4 gidgethub==3.1.0 PyJWT==1.7.1 github3.py==1.3.0
    - python3 ci/upload_binary.py $CI_COMMIT_REF_NAME
